version: "3.8"

services:
  # Base de données
  db:
    image: postgres:15
    container_name: gestion_locaux_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-gestion_locaux}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - ./database/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./database/02_data_test.sql:/docker-entrypoint-initdb.d/02_data_test.sql
      - pgdata:/var/lib/postgresql/data

  # Backend Node.js
  backend:
    build: ./back
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./back:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://${DB_USER:-user}:${DB_PASSWORD:-password}@db:5432/${DB_NAME:-gestion_locaux}
      MOCK_MODE: ${MOCK_MODE:-true}

  # Frontend Angular
  frontend:
    build: ./front
    ports:
      - "4200:4200"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Pour le live-reload sous Windows/Docker

  # Interface de gestion Base de Données
  pgadmin:
    image: dpage/pgadmin4
    container_name: gestion_locaux_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
      PGPASSFILE: /var/lib/pgadmin/pgpass
    ports:
      - "5050:80"
    volumes:
      - ./database/pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./database/pgadmin/pgpass:/var/lib/pgadmin/pgpass:ro
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  pgdata:
  pgadmin_data:
