version: "3.8"

services:
  # Base de données
  db:
    image: postgres:15
    container_name: gestion_locaux_db
    restart: alwaysdb:
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./dataBase/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  # Backend Node.js
  backend:
    build: ./back
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    volumes:
      - ./backend:/app
      - /app/node_modules
  # Frontend Angular
  frontend:
    build: ./front
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Interface de gestion Base de Données
  pgadmin:
    image: dpage/pgadmin4
    container_name: gestion_locaux_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
